/*
 GNU Lesser General Public License, http://www.gnu.org/copyleft/lesser.html
 @author  Jan Odvarko, http://odvarko.cz
 @created 2008-06-15
 @updated 2012-01-19
 @link    http://jscolor.com
*/
var jscolor={dir:"",bindClass:"color",binding:!0,preloading:!0,install:function(){jscolor.addEvent(window,"load",jscolor.init)},init:function(){jscolor.binding&&jscolor.bind();jscolor.preloading&&jscolor.preload()},getDir:function(){if(!jscolor.dir){var b=jscolor.detectDir();jscolor.dir=!1!==b?b:"jscolor/"}return jscolor.dir},detectDir:function(){for(var b=location.href,e=document.getElementsByTagName("base"),c=0;c<e.length;c+=1)e[c].href&&(b=e[c].href);e=document.getElementsByTagName("script");for(c=
0;c<e.length;c+=1)if(e[c].src&&/(^|\/)jscolor\.js([?#].*)?$/i.test(e[c].src))return b=(new jscolor.URI(e[c].src)).toAbsolute(b),b.path=b.path.replace(/[^\/]+$/,""),b.query=null,b.fragment=null,b.toString();return!1},bind:function(){for(var b=RegExp("(^|\\s)("+jscolor.bindClass+")\\s*(\\{[^}]*\\})?","i"),e=document.getElementsByTagName("input"),c=0;c<e.length;c+=1){var l;if(!e[c].color&&e[c].className&&(l=e[c].className.match(b))){if(l[3])try{eval("prop="+l[3])}catch(w){}e[c].color=new jscolor.color(e[c],
{})}}},preload:function(){for(var b in jscolor.imgRequire)jscolor.imgRequire.hasOwnProperty(b)&&jscolor.loadImage(b)},images:{pad:[181,101],sld:[16,101],cross:[15,15],arrow:[7,11]},imgRequire:{},imgLoaded:{},requireImage:function(b){jscolor.imgRequire[b]=!0},loadImage:function(b){jscolor.imgLoaded[b]||(jscolor.imgLoaded[b]=new Image,jscolor.imgLoaded[b].src=jscolor.getDir()+b)},fetchElement:function(b){return"string"===typeof b?document.getElementById(b):b},addEvent:function(b,e,c){b.addEventListener?
b.addEventListener(e,c,!1):b.attachEvent&&b.attachEvent("on"+e,c)},fireEvent:function(b,e){if(b)if(document.createEvent){var c=document.createEvent("HTMLEvents");c.initEvent(e,!0,!0);b.dispatchEvent(c)}else if(document.createEventObject)c=document.createEventObject(),b.fireEvent("on"+e,c);else if(b["on"+e])b["on"+e]()},getElementPos:function(b){var e=b,c=0,l=0;if(e.offsetParent){do c+=e.offsetLeft,l+=e.offsetTop;while(e=e.offsetParent)}for(;(b=b.parentNode)&&"BODY"!==b.nodeName.toUpperCase();)c-=
b.scrollLeft,l-=b.scrollTop;return[c,l]},getElementSize:function(b){return[b.offsetWidth,b.offsetHeight]},getRelMousePos:function(b){var e=0,c=0;b||(b=window.event);"number"===typeof b.offsetX?(e=b.offsetX,c=b.offsetY):"number"===typeof b.layerX&&(e=b.layerX,c=b.layerY);return{x:e,y:c}},getViewPos:function(){return"number"===typeof window.pageYOffset?[window.pageXOffset,window.pageYOffset]:document.body&&(document.body.scrollLeft||document.body.scrollTop)?[document.body.scrollLeft,document.body.scrollTop]:
document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[0,0]},getViewSize:function(){return"number"===typeof window.innerWidth?[window.innerWidth,window.innerHeight]:document.body&&(document.body.clientWidth||document.body.clientHeight)?[document.body.clientWidth,document.body.clientHeight]:document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?
[document.documentElement.clientWidth,document.documentElement.clientHeight]:[0,0]},URI:function(b){function e(c){for(var b="";c;)if("../"===c.substr(0,3)||"./"===c.substr(0,2))c=c.replace(/^\.+/,"").substr(1);else if("/./"===c.substr(0,3)||"/."===c)c="/"+c.substr(3);else if("/../"===c.substr(0,4)||"/.."===c)c="/"+c.substr(4),b=b.replace(/\/?[^\/]*$/,"");else if("."===c||".."===c)c="";else var e=c.match(/^\/?[^\/]*/)[0],c=c.substr(e.length),b=b+e;return b}this.authority=this.scheme=null;this.path=
"";this.fragment=this.query=null;this.parse=function(c){c=c.match(/^(([A-Za-z][0-9A-Za-z+.-]*)(:))?((\/\/)([^\/?#]*))?([^?#]*)((\?)([^#]*))?((#)(.*))?/);this.scheme=c[3]?c[2]:null;this.authority=c[5]?c[6]:null;this.path=c[7];this.query=c[9]?c[10]:null;this.fragment=c[12]?c[13]:null;return this};this.toString=function(){var c="";null!==this.scheme&&(c=c+this.scheme+":");null!==this.authority&&(c=c+"//"+this.authority);null!==this.path&&(c+=this.path);null!==this.query&&(c=c+"?"+this.query);null!==
this.fragment&&(c=c+"#"+this.fragment);return c};this.toAbsolute=function(c){var c=new jscolor.URI(c),b=new jscolor.URI;if(null===c.scheme)return!1;null!==this.scheme&&this.scheme.toLowerCase()===c.scheme.toLowerCase()&&(this.scheme=null);null!==this.scheme?(b.scheme=this.scheme,b.authority=this.authority,b.path=e(this.path),b.query=this.query):(null!==this.authority?(b.authority=this.authority,b.path=e(this.path),b.query=this.query):(""===this.path?(b.path=c.path,b.query=null!==this.query?this.query:
c.query):("/"===this.path.substr(0,1)?b.path=e(this.path):(b.path=null!==c.authority&&""===c.path?"/"+this.path:c.path.replace(/[^\/]+$/,"")+this.path,b.path=e(b.path)),b.query=this.query),b.authority=c.authority),b.scheme=c.scheme);b.fragment=this.fragment;return b};b&&this.parse(b)},color:function(b,e){function c(a,c,b){if(null===a)return[b,b,b];var d=Math.floor(a),e=b*(1-c),a=b*(1-c*(d%2?a-d:1-(a-d)));switch(d){case 6:case 0:return[b,a,e];case 1:return[a,b,e];case 2:return[e,b,a];case 3:return[e,
a,b];case 4:return[a,e,b];case 5:return[b,e,a]}}function l(a){return[2*a.pickerInset+2*a.pickerFace+jscolor.images.pad[0]+(a.slider?2*a.pickerInset+2*jscolor.images.arrow[0]+jscolor.images.sld[0]:0),a.pickerClosable?4*a.pickerInset+3*a.pickerFace+jscolor.images.pad[1]+a.pickerButtonHeight:2*a.pickerInset+2*a.pickerFace+jscolor.images.pad[1]]}function w(){switch(n){case 0:var a=1;break;case 1:a=2}var b=Math.round(d.hsv[0]/6*(jscolor.images.pad[0]-1)),a=Math.round((1-d.hsv[a])*(jscolor.images.pad[1]-
1));jscolor.picker.padM.style.backgroundPosition=d.pickerFace+d.pickerInset+b-Math.floor(jscolor.images.cross[0]/2)+"px "+(d.pickerFace+d.pickerInset+a-Math.floor(jscolor.images.cross[1]/2))+"px";b=jscolor.picker.sld.childNodes;switch(n){case 0:for(var e=c(d.hsv[0],d.hsv[1],1),a=0;a<b.length;a+=1)b[a].style.backgroundColor="rgb("+100*e[0]*(1-a/b.length)+"%,"+100*e[1]*(1-a/b.length)+"%,"+100*e[2]*(1-a/b.length)+"%)";break;case 1:var g,k=[d.hsv[2],0,0],a=Math.floor(d.hsv[0]),h=a%2?d.hsv[0]-a:1-(d.hsv[0]-
a);switch(a){case 6:case 0:e=[0,1,2];break;case 1:e=[1,0,2];break;case 2:e=[2,0,1];break;case 3:e=[2,1,0];break;case 4:e=[1,2,0];break;case 5:e=[0,2,1]}for(a=0;a<b.length;a+=1)g=1-1/(b.length-1)*a,k[1]=k[0]*(1-g*h),k[2]=k[0]*(1-g),b[a].style.backgroundColor="rgb("+100*k[e[0]]+"%,"+100*k[e[1]]+"%,"+100*k[e[2]]+"%)"}}function z(){switch(n){case 0:var a=2;break;case 1:a=1}a=Math.round((1-d.hsv[a])*(jscolor.images.sld[1]-1));jscolor.picker.sldM.style.backgroundPosition="0 "+(d.pickerFace+d.pickerInset+
a-Math.floor(jscolor.images.arrow[1]/2))+"px"}function u(){return jscolor.picker&&jscolor.picker.owner===d}function C(){i!==b&&d.importColor()}function A(a){var b=jscolor.getRelMousePos(a),a=b.x-d.pickerFace-d.pickerInset,b=b.y-d.pickerFace-d.pickerInset;switch(n){case 0:d.fromHSV(a*(6/(jscolor.images.pad[0]-1)),1-b/(jscolor.images.pad[1]-1),null,p);break;case 1:d.fromHSV(a*(6/(jscolor.images.pad[0]-1)),null,1-b/(jscolor.images.pad[1]-1),p)}}function B(a){a=jscolor.getRelMousePos(a).y-d.pickerFace-
d.pickerInset;switch(n){case 0:d.fromHSV(null,null,1-a/(jscolor.images.sld[1]-1),x);break;case 1:d.fromHSV(null,1-a/(jscolor.images.sld[1]-1),null,x)}}function v(){if(d.onImmediateChange)if("string"===typeof d.onImmediateChange)eval(d.onImmediateChange);else d.onImmediateChange(d)}this.adjust=this.required=!0;this.hash=!1;this.slider=this.caps=!0;this.styleElement=this.valueElement=b;this.onImmediateChange=null;this.hsv=[0,0,1];this.rgb=[1,1,1];this.pickerOnfocus=!0;this.pickerMode="HSV";this.pickerPosition=
"bottom";this.pickerSmartPosition=!0;this.pickerButtonHeight=20;this.pickerClosable=!1;this.pickerCloseText="Close";this.pickerButtonColor="ButtonText";this.pickerFace=10;this.pickerFaceColor="ThreeDFace";this.pickerBorder=1;this.pickerBorderColor="ThreeDHighlight ThreeDShadow ThreeDShadow ThreeDHighlight";this.pickerInset=1;this.pickerInsetColor="ThreeDShadow ThreeDHighlight ThreeDHighlight ThreeDShadow";this.pickerZIndex=1E4;for(var o in e)e.hasOwnProperty(o)&&(this[o]=e[o]);this.hidePicker=function(){u()&&
(delete jscolor.picker.owner,document.getElementsByTagName("body")[0].removeChild(jscolor.picker.boxB))};this.showPicker=function(){if(!u()){var a=jscolor.getElementPos(b),c=jscolor.getElementSize(b),e=jscolor.getViewPos(),g=jscolor.getViewSize(),k=l(this),h,f,m;switch(this.pickerPosition.toLowerCase()){case "left":h=1;f=0;m=-1;break;case "right":h=1;f=0;m=1;break;case "top":h=0;f=1;m=-1;break;default:h=0,m=f=1}var j=(c[f]+k[f])/2,a=this.pickerSmartPosition?[-e[h]+a[h]+k[h]>g[h]?-e[h]+a[h]+c[h]/2>
g[h]/2&&0<=a[h]+c[h]-k[h]?a[h]+c[h]-k[h]:a[h]:a[h],-e[f]+a[f]+c[f]+k[f]-j+j*m>g[f]?-e[f]+a[f]+c[f]/2>g[f]/2&&0<=a[f]+c[f]-j-j*m?a[f]+c[f]-j-j*m:a[f]+c[f]-j+j*m:0<=a[f]+c[f]-j+j*m?a[f]+c[f]-j+j*m:a[f]+c[f]-j-j*m]:[a[h],a[f]+c[f]-j+j*m];h=a[h];f=a[f];if(!jscolor.picker){jscolor.picker={box:document.createElement("div"),boxB:document.createElement("div"),pad:document.createElement("div"),padB:document.createElement("div"),padM:document.createElement("div"),sld:document.createElement("div"),sldB:document.createElement("div"),
sldM:document.createElement("div"),btn:document.createElement("div"),btnS:document.createElement("span"),btnT:document.createTextNode(d.pickerCloseText)};for(a=0;a<jscolor.images.sld[1];a+=4)c=document.createElement("div"),c.style.height="4px",c.style.fontSize="1px",c.style.lineHeight="0",jscolor.picker.sld.appendChild(c);jscolor.picker.sldB.appendChild(jscolor.picker.sld);jscolor.picker.box.appendChild(jscolor.picker.sldB);jscolor.picker.box.appendChild(jscolor.picker.sldM);jscolor.picker.padB.appendChild(jscolor.picker.pad);
jscolor.picker.box.appendChild(jscolor.picker.padB);jscolor.picker.box.appendChild(jscolor.picker.padM);jscolor.picker.btnS.appendChild(jscolor.picker.btnT);jscolor.picker.btn.appendChild(jscolor.picker.btnS);jscolor.picker.box.appendChild(jscolor.picker.btn);jscolor.picker.boxB.appendChild(jscolor.picker.box)}a=jscolor.picker;a.box.onmouseup=a.box.onmouseout=function(){b.focus()};a.box.onmousedown=function(){r=!0};a.box.onmousemove=function(a){if(s||t)s&&A(a),t&&B(a),document.selection?document.selection.empty():
window.getSelection&&window.getSelection().removeAllRanges(),v()};a.padM.onmouseup=a.padM.onmouseout=function(){s&&(s=!1,jscolor.fireEvent(i,"change"))};a.padM.onmousedown=function(a){switch(n){case 0:0===d.hsv[2]&&d.fromHSV(null,null,1);break;case 1:0===d.hsv[1]&&d.fromHSV(null,1,null)}s=!0;A(a);v()};a.sldM.onmouseup=a.sldM.onmouseout=function(){t&&(t=!1,jscolor.fireEvent(i,"change"))};a.sldM.onmousedown=function(a){t=!0;B(a);v()};c=l(d);a.box.style.width=c[0]+"px";a.box.style.height=c[1]+"px";a.boxB.style.position=
"absolute";a.boxB.style.clear="both";a.boxB.style.left=h+"px";a.boxB.style.top=f+"px";a.boxB.style.zIndex=d.pickerZIndex;a.boxB.style.border=d.pickerBorder+"px solid";a.boxB.style.borderColor=d.pickerBorderColor;a.boxB.style.background=d.pickerFaceColor;a.pad.style.width=jscolor.images.pad[0]+"px";a.pad.style.height=jscolor.images.pad[1]+"px";a.padB.style.position="absolute";a.padB.style.left=d.pickerFace+"px";a.padB.style.top=d.pickerFace+"px";a.padB.style.border=d.pickerInset+"px solid";a.padB.style.borderColor=
d.pickerInsetColor;a.padM.style.position="absolute";a.padM.style.left="0";a.padM.style.top="0";a.padM.style.width=d.pickerFace+2*d.pickerInset+jscolor.images.pad[0]+jscolor.images.arrow[0]+"px";a.padM.style.height=a.box.style.height;a.padM.style.cursor="crosshair";a.sld.style.overflow="hidden";a.sld.style.width=jscolor.images.sld[0]+"px";a.sld.style.height=jscolor.images.sld[1]+"px";a.sldB.style.display=d.slider?"block":"none";a.sldB.style.position="absolute";a.sldB.style.right=d.pickerFace+"px";
a.sldB.style.top=d.pickerFace+"px";a.sldB.style.border=d.pickerInset+"px solid";a.sldB.style.borderColor=d.pickerInsetColor;a.sldM.style.display=d.slider?"block":"none";a.sldM.style.position="absolute";a.sldM.style.right="0";a.sldM.style.top="0";a.sldM.style.width=jscolor.images.sld[0]+jscolor.images.arrow[0]+d.pickerFace+2*d.pickerInset+"px";a.sldM.style.height=a.box.style.height;try{a.sldM.style.cursor="pointer"}catch(o){a.sldM.style.cursor="hand"}a.btn.style.display=d.pickerClosable?"block":"none";
a.btn.style.position="absolute";a.btn.style.left=d.pickerFace+"px";a.btn.style.bottom=d.pickerFace+"px";a.btn.style.padding="0 15px";a.btn.style.height="18px";a.btn.style.border=d.pickerInset+"px solid";f=d.pickerInsetColor.split(/\s+/);a.btn.style.borderColor=2>f.length?f[0]:f[1]+" "+f[0]+" "+f[0]+" "+f[1];a.btn.style.color=d.pickerButtonColor;a.btn.style.font="12px sans-serif";a.btn.style.textAlign="center";try{a.btn.style.cursor="pointer"}catch(q){a.btn.style.cursor="hand"}a.btn.onmousedown=function(){d.hidePicker()};
a.btnS.style.lineHeight=a.btn.style.height;switch(n){case 0:var p="hs.png";break;case 1:p="hv.png"}a.padM.style.backgroundImage="url('"+jscolor.getDir()+"cross.gif')";a.padM.style.backgroundRepeat="no-repeat";a.sldM.style.backgroundImage="url('"+jscolor.getDir()+"arrow.gif')";a.sldM.style.backgroundRepeat="no-repeat";a.pad.style.backgroundImage="url('"+jscolor.getDir()+p+"')";a.pad.style.backgroundRepeat="no-repeat";a.pad.style.backgroundPosition="0 0";w();z();jscolor.picker.owner=d;document.getElementsByTagName("body")[0].appendChild(a.boxB)}};
this.importColor=function(){i?this.adjust?!this.required&&/^\s*$/.test(i.value)?(i.value="",g.style.backgroundImage=g.jscStyle.backgroundImage,g.style.backgroundColor=g.jscStyle.backgroundColor,g.style.color=g.jscStyle.color,this.exportColor(q|y)):this.fromString(i.value)||this.exportColor():this.fromString(i.value,q)||(g.style.backgroundImage=g.jscStyle.backgroundImage,g.style.backgroundColor=g.jscStyle.backgroundColor,g.style.color=g.jscStyle.color,this.exportColor(q|y)):this.exportColor()};this.exportColor=
function(a){if(!(a&q)&&i){var b=this.toString();this.caps&&(b=b.toUpperCase());this.hash&&(b="#"+b);i.value=b}!(a&y)&&g&&(g.style.backgroundImage="none",g.style.backgroundColor="#"+this.toString(),g.style.color=0.5>0.213*this.rgb[0]+0.715*this.rgb[1]+0.072*this.rgb[2]?"#FFF":"#000");!(a&x)&&u()&&w();!(a&p)&&u()&&z()};this.fromHSV=function(a,b,d,e){0>a&&(a=0)||6<a&&(a=6);0>b&&(b=0)||1<b&&(b=1);0>d&&(d=0)||1<d&&(d=1);this.rgb=c(null===a?this.hsv[0]:this.hsv[0]=a,null===b?this.hsv[1]:this.hsv[1]=b,null===
d?this.hsv[2]:this.hsv[2]=d);this.exportColor(e)};this.fromRGB=function(a,b,c,d){0>a&&(a=0)||1<a&&(a=1);0>b&&(b=0)||1<b&&(b=1);0>c&&(c=0)||1<c&&(c=1);var a=null===a?this.rgb[0]:this.rgb[0]=a,b=null===b?this.rgb[1]:this.rgb[1]=b,e=null===c?this.rgb[2]:this.rgb[2]=c,g=Math.min(Math.min(a,b),e),c=Math.max(Math.max(a,b),e),f=c-g;0===f?a=[null,0,c]:(a=a===g?3+(e-b)/f:b===g?5+(a-e)/f:1+(b-a)/f,a=[6===a?0:a,f/c,c]);null!==a[0]&&(this.hsv[0]=a[0]);0!==a[2]&&(this.hsv[1]=a[1]);this.hsv[2]=a[2];this.exportColor(d)};
this.fromString=function(a,b){var c=a.match(/^\W*([0-9A-F]{3}([0-9A-F]{3})?)\W*$/i);return c?(6===c[1].length?this.fromRGB(parseInt(c[1].substr(0,2),16)/255,parseInt(c[1].substr(2,2),16)/255,parseInt(c[1].substr(4,2),16)/255,b):this.fromRGB(parseInt(c[1].charAt(0)+c[1].charAt(0),16)/255,parseInt(c[1].charAt(1)+c[1].charAt(1),16)/255,parseInt(c[1].charAt(2)+c[1].charAt(2),16)/255,b),!0):!1};this.toString=function(){return(256|Math.round(255*this.rgb[0])).toString(16).substr(1)+(256|Math.round(255*
this.rgb[1])).toString(16).substr(1)+(256|Math.round(255*this.rgb[2])).toString(16).substr(1)};var d=this,n="hvs"===this.pickerMode.toLowerCase()?1:0,r=!1,i=jscolor.fetchElement(this.valueElement),g=jscolor.fetchElement(this.styleElement),s=!1,t=!1,q=1,y=2,x=4,p=8;jscolor.addEvent(b,"focus",function(){d.pickerOnfocus&&d.showPicker()});jscolor.addEvent(b,"blur",function(){r?r=!1:window.setTimeout(function(){r||(i===b&&d.importColor(),d.pickerOnfocus&&d.hidePicker());r=!1},0)});i&&(o=function(){d.fromString(i.value,
q);v()},jscolor.addEvent(i,"keyup",o),jscolor.addEvent(i,"input",o),jscolor.addEvent(i,"blur",C),i.setAttribute("autocomplete","off"));g&&(g.jscStyle={backgroundImage:g.style.backgroundImage,backgroundColor:g.style.backgroundColor,color:g.style.color});switch(n){case 0:jscolor.requireImage("hs.png");break;case 1:jscolor.requireImage("hv.png")}jscolor.requireImage("cross.gif");jscolor.requireImage("arrow.gif");this.importColor()}};jscolor.install();
